sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t youstest/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run youstest/react-test npm test -- --coverage

after_success:
  - docker build -t youstest/multi-client ./client
  - docker build -t youstest/multi-nginx ./nginx
  - docker build -t youstest/multi-server ./server
  - docker build -t youstest/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push youstest/multi-client
  - docker push youstest/multi-nginx
  - docker push youstest/multi-server
  - docker push youstest/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-631216135234
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
